"""
Mainstream football tactics as continuous vectors — no if action == 'gegenpress'.
Each named style is a region in R^n; coaches blend presets + four legacy knobs.
"""

from __future__ import annotations

import re
from typing import Dict, List, Tuple

# Legacy four knobs (GFS) + extended micro dimensions
TACTICAL_KEYS: Tuple[str, ...] = (
    "pressing_intensity",
    "risk_budget",
    "line_height",
    "rotation_aggressiveness",
    "possession_orientation",
    "verticality",
    "width_play",
    "tempo",
    "counter_attack",
    "high_press",
    "low_block",
    "wing_focus",
    "cross_frequency",
    "through_ball_bias",
    "long_ball_bias",
    "build_up_short",
    "offside_trap",
    "counterpress",
    "man_oriented_press",
    "target_man",
    "overlap_fullbacks",
    "compactness",
)

# Named mainstream presets (values 0–1)
TACTICAL_PRESETS: Dict[str, Dict[str, float]] = {
    "balanced": {
        "pressing_intensity": 0.50,
        "risk_budget": 0.50,
        "line_height": 0.50,
        "rotation_aggressiveness": 0.50,
        "possession_orientation": 0.50,
        "verticality": 0.50,
        "width_play": 0.50,
        "tempo": 0.50,
        "counter_attack": 0.45,
        "high_press": 0.45,
        "low_block": 0.35,
        "wing_focus": 0.50,
        "cross_frequency": 0.45,
        "through_ball_bias": 0.45,
        "long_ball_bias": 0.35,
        "build_up_short": 0.50,
        "offside_trap": 0.40,
        "counterpress": 0.45,
        "man_oriented_press": 0.40,
        "target_man": 0.40,
        "overlap_fullbacks": 0.50,
        "compactness": 0.55,
    },
    # Possession / positional
    "tiki_taka": {
        "pressing_intensity": 0.62,
        "risk_budget": 0.42,
        "line_height": 0.62,
        "rotation_aggressiveness": 0.72,
        "possession_orientation": 0.94,
        "verticality": 0.38,
        "width_play": 0.58,
        "tempo": 0.48,
        "counter_attack": 0.25,
        "high_press": 0.55,
        "low_block": 0.18,
        "wing_focus": 0.45,
        "cross_frequency": 0.28,
        "through_ball_bias": 0.52,
        "long_ball_bias": 0.12,
        "build_up_short": 0.92,
        "offside_trap": 0.55,
        "counterpress": 0.68,
        "man_oriented_press": 0.35,
        "target_man": 0.25,
        "overlap_fullbacks": 0.55,
        "compactness": 0.62,
    },
    "positional_play": {
        "pressing_intensity": 0.58,
        "risk_budget": 0.40,
        "line_height": 0.60,
        "rotation_aggressiveness": 0.78,
        "possession_orientation": 0.90,
        "verticality": 0.42,
        "width_play": 0.62,
        "tempo": 0.52,
        "counter_attack": 0.28,
        "high_press": 0.52,
        "low_block": 0.22,
        "wing_focus": 0.48,
        "cross_frequency": 0.32,
        "through_ball_bias": 0.48,
        "long_ball_bias": 0.15,
        "build_up_short": 0.88,
        "offside_trap": 0.50,
        "counterpress": 0.62,
        "man_oriented_press": 0.30,
        "target_man": 0.30,
        "overlap_fullbacks": 0.58,
        "compactness": 0.65,
    },
    # Pressing schools
    "gegenpress": {
        "pressing_intensity": 0.92,
        "risk_budget": 0.68,
        "line_height": 0.72,
        "rotation_aggressiveness": 0.65,
        "possession_orientation": 0.55,
        "verticality": 0.78,
        "width_play": 0.55,
        "tempo": 0.88,
        "counter_attack": 0.62,
        "high_press": 0.95,
        "low_block": 0.10,
        "wing_focus": 0.52,
        "cross_frequency": 0.35,
        "through_ball_bias": 0.58,
        "long_ball_bias": 0.22,
        "build_up_short": 0.55,
        "offside_trap": 0.62,
        "counterpress": 0.94,
        "man_oriented_press": 0.55,
        "target_man": 0.35,
        "overlap_fullbacks": 0.62,
        "compactness": 0.48,
    },
    "high_press": {
        "pressing_intensity": 0.88,
        "risk_budget": 0.62,
        "line_height": 0.70,
        "rotation_aggressiveness": 0.58,
        "possession_orientation": 0.52,
        "verticality": 0.72,
        "width_play": 0.54,
        "tempo": 0.82,
        "counter_attack": 0.55,
        "high_press": 0.90,
        "low_block": 0.12,
        "wing_focus": 0.50,
        "cross_frequency": 0.38,
        "through_ball_bias": 0.55,
        "long_ball_bias": 0.25,
        "build_up_short": 0.50,
        "offside_trap": 0.58,
        "counterpress": 0.85,
        "man_oriented_press": 0.48,
        "target_man": 0.32,
        "overlap_fullbacks": 0.58,
        "compactness": 0.50,
    },
    "bielsa_man_marking": {
        "pressing_intensity": 0.95,
        "risk_budget": 0.75,
        "line_height": 0.68,
        "rotation_aggressiveness": 0.70,
        "possession_orientation": 0.48,
        "verticality": 0.82,
        "width_play": 0.60,
        "tempo": 0.90,
        "counter_attack": 0.58,
        "high_press": 0.92,
        "low_block": 0.08,
        "wing_focus": 0.55,
        "cross_frequency": 0.40,
        "through_ball_bias": 0.50,
        "long_ball_bias": 0.28,
        "build_up_short": 0.45,
        "offside_trap": 0.45,
        "counterpress": 0.88,
        "man_oriented_press": 0.92,
        "target_man": 0.30,
        "overlap_fullbacks": 0.65,
        "compactness": 0.42,
    },
    # Defensive blocks
    "low_block_counter": {
        "pressing_intensity": 0.32,
        "risk_budget": 0.38,
        "line_height": 0.28,
        "rotation_aggressiveness": 0.42,
        "possession_orientation": 0.35,
        "verticality": 0.72,
        "width_play": 0.48,
        "tempo": 0.62,
        "counter_attack": 0.88,
        "high_press": 0.18,
        "low_block": 0.90,
        "wing_focus": 0.55,
        "cross_frequency": 0.42,
        "through_ball_bias": 0.62,
        "long_ball_bias": 0.45,
        "build_up_short": 0.35,
        "offside_trap": 0.15,
        "counterpress": 0.25,
        "man_oriented_press": 0.35,
        "target_man": 0.45,
        "overlap_fullbacks": 0.35,
        "compactness": 0.82,
    },
    "catenaccio": {
        "pressing_intensity": 0.25,
        "risk_budget": 0.28,
        "line_height": 0.22,
        "rotation_aggressiveness": 0.35,
        "possession_orientation": 0.30,
        "verticality": 0.55,
        "width_play": 0.42,
        "tempo": 0.40,
        "counter_attack": 0.75,
        "high_press": 0.12,
        "low_block": 0.95,
        "wing_focus": 0.40,
        "cross_frequency": 0.30,
        "through_ball_bias": 0.40,
        "long_ball_bias": 0.50,
        "build_up_short": 0.30,
        "offside_trap": 0.20,
        "counterpress": 0.18,
        "man_oriented_press": 0.45,
        "target_man": 0.50,
        "overlap_fullbacks": 0.28,
        "compactness": 0.92,
    },
    "park_the_bus": {
        "pressing_intensity": 0.18,
        "risk_budget": 0.22,
        "line_height": 0.18,
        "rotation_aggressiveness": 0.30,
        "possession_orientation": 0.22,
        "verticality": 0.48,
        "width_play": 0.38,
        "tempo": 0.35,
        "counter_attack": 0.82,
        "high_press": 0.08,
        "low_block": 0.98,
        "wing_focus": 0.35,
        "cross_frequency": 0.25,
        "through_ball_bias": 0.35,
        "long_ball_bias": 0.55,
        "build_up_short": 0.25,
        "offside_trap": 0.12,
        "counterpress": 0.12,
        "man_oriented_press": 0.50,
        "target_man": 0.55,
        "overlap_fullbacks": 0.22,
        "compactness": 0.96,
    },
    "mid_block": {
        "pressing_intensity": 0.48,
        "risk_budget": 0.45,
        "line_height": 0.48,
        "rotation_aggressiveness": 0.50,
        "possession_orientation": 0.48,
        "verticality": 0.55,
        "width_play": 0.50,
        "tempo": 0.52,
        "counter_attack": 0.55,
        "high_press": 0.35,
        "low_block": 0.55,
        "wing_focus": 0.48,
        "cross_frequency": 0.42,
        "through_ball_bias": 0.48,
        "long_ball_bias": 0.38,
        "build_up_short": 0.48,
        "offside_trap": 0.38,
        "counterpress": 0.48,
        "man_oriented_press": 0.42,
        "target_man": 0.42,
        "overlap_fullbacks": 0.48,
        "compactness": 0.68,
    },
    # Direct / vertical
    "direct_vertical": {
        "pressing_intensity": 0.55,
        "risk_budget": 0.58,
        "line_height": 0.52,
        "rotation_aggressiveness": 0.48,
        "possession_orientation": 0.32,
        "verticality": 0.88,
        "width_play": 0.48,
        "tempo": 0.75,
        "counter_attack": 0.72,
        "high_press": 0.48,
        "low_block": 0.30,
        "wing_focus": 0.45,
        "cross_frequency": 0.38,
        "through_ball_bias": 0.65,
        "long_ball_bias": 0.62,
        "build_up_short": 0.35,
        "offside_trap": 0.35,
        "counterpress": 0.52,
        "man_oriented_press": 0.38,
        "target_man": 0.55,
        "overlap_fullbacks": 0.42,
        "compactness": 0.58,
    },
    "long_ball": {
        "pressing_intensity": 0.42,
        "risk_budget": 0.52,
        "line_height": 0.45,
        "rotation_aggressiveness": 0.40,
        "possession_orientation": 0.25,
        "verticality": 0.85,
        "width_play": 0.55,
        "tempo": 0.68,
        "counter_attack": 0.65,
        "high_press": 0.35,
        "low_block": 0.45,
        "wing_focus": 0.60,
        "cross_frequency": 0.72,
        "through_ball_bias": 0.45,
        "long_ball_bias": 0.88,
        "build_up_short": 0.22,
        "offside_trap": 0.28,
        "counterpress": 0.38,
        "man_oriented_press": 0.35,
        "target_man": 0.78,
        "overlap_fullbacks": 0.38,
        "compactness": 0.62,
    },
    "route_one": {
        "pressing_intensity": 0.38,
        "risk_budget": 0.48,
        "line_height": 0.40,
        "rotation_aggressiveness": 0.35,
        "possession_orientation": 0.20,
        "verticality": 0.90,
        "width_play": 0.52,
        "tempo": 0.72,
        "counter_attack": 0.70,
        "high_press": 0.28,
        "low_block": 0.50,
        "wing_focus": 0.48,
        "cross_frequency": 0.55,
        "through_ball_bias": 0.40,
        "long_ball_bias": 0.92,
        "build_up_short": 0.18,
        "offside_trap": 0.22,
        "counterpress": 0.30,
        "man_oriented_press": 0.32,
        "target_man": 0.85,
        "overlap_fullbacks": 0.32,
        "compactness": 0.70,
    },
    # Wing play
    "wing_play": {
        "pressing_intensity": 0.52,
        "risk_budget": 0.55,
        "line_height": 0.52,
        "rotation_aggressiveness": 0.55,
        "possession_orientation": 0.45,
        "verticality": 0.58,
        "width_play": 0.88,
        "tempo": 0.62,
        "counter_attack": 0.50,
        "high_press": 0.45,
        "low_block": 0.32,
        "wing_focus": 0.92,
        "cross_frequency": 0.85,
        "through_ball_bias": 0.42,
        "long_ball_bias": 0.40,
        "build_up_short": 0.48,
        "offside_trap": 0.40,
        "counterpress": 0.48,
        "man_oriented_press": 0.38,
        "target_man": 0.60,
        "overlap_fullbacks": 0.82,
        "compactness": 0.55,
    },
    "crossing_target": {
        "pressing_intensity": 0.48,
        "risk_budget": 0.50,
        "line_height": 0.48,
        "rotation_aggressiveness": 0.48,
        "possession_orientation": 0.40,
        "verticality": 0.62,
        "width_play": 0.82,
        "tempo": 0.58,
        "counter_attack": 0.48,
        "high_press": 0.42,
        "low_block": 0.38,
        "wing_focus": 0.88,
        "cross_frequency": 0.92,
        "through_ball_bias": 0.35,
        "long_ball_bias": 0.48,
        "build_up_short": 0.42,
        "offside_trap": 0.35,
        "counterpress": 0.42,
        "man_oriented_press": 0.36,
        "target_man": 0.88,
        "overlap_fullbacks": 0.75,
        "compactness": 0.58,
    },
    # Transitions
    "counter_attack": {
        "pressing_intensity": 0.40,
        "risk_budget": 0.52,
        "line_height": 0.35,
        "rotation_aggressiveness": 0.45,
        "possession_orientation": 0.30,
        "verticality": 0.82,
        "width_play": 0.55,
        "tempo": 0.78,
        "counter_attack": 0.95,
        "high_press": 0.30,
        "low_block": 0.75,
        "wing_focus": 0.58,
        "cross_frequency": 0.45,
        "through_ball_bias": 0.72,
        "long_ball_bias": 0.48,
        "build_up_short": 0.32,
        "offside_trap": 0.22,
        "counterpress": 0.35,
        "man_oriented_press": 0.40,
        "target_man": 0.48,
        "overlap_fullbacks": 0.48,
        "compactness": 0.75,
    },
    "transitional_vertical": {
        "pressing_intensity": 0.58,
        "risk_budget": 0.62,
        "line_height": 0.55,
        "rotation_aggressiveness": 0.52,
        "possession_orientation": 0.38,
        "verticality": 0.90,
        "width_play": 0.52,
        "tempo": 0.85,
        "counter_attack": 0.88,
        "high_press": 0.55,
        "low_block": 0.28,
        "wing_focus": 0.50,
        "cross_frequency": 0.38,
        "through_ball_bias": 0.70,
        "long_ball_bias": 0.42,
        "build_up_short": 0.40,
        "offside_trap": 0.48,
        "counterpress": 0.72,
        "man_oriented_press": 0.42,
        "target_man": 0.40,
        "overlap_fullbacks": 0.55,
        "compactness": 0.52,
    },
    # Special shapes / roles
    "false_nine": {
        "pressing_intensity": 0.60,
        "risk_budget": 0.48,
        "line_height": 0.58,
        "rotation_aggressiveness": 0.75,
        "possession_orientation": 0.78,
        "verticality": 0.55,
        "width_play": 0.65,
        "tempo": 0.58,
        "counter_attack": 0.40,
        "high_press": 0.58,
        "low_block": 0.22,
        "wing_focus": 0.55,
        "cross_frequency": 0.32,
        "through_ball_bias": 0.68,
        "long_ball_bias": 0.20,
        "build_up_short": 0.75,
        "offside_trap": 0.52,
        "counterpress": 0.65,
        "man_oriented_press": 0.38,
        "target_man": 0.15,
        "overlap_fullbacks": 0.62,
        "compactness": 0.60,
    },
    "double_pivot_control": {
        "pressing_intensity": 0.52,
        "risk_budget": 0.38,
        "line_height": 0.50,
        "rotation_aggressiveness": 0.55,
        "possession_orientation": 0.72,
        "verticality": 0.45,
        "width_play": 0.52,
        "tempo": 0.48,
        "counter_attack": 0.35,
        "high_press": 0.48,
        "low_block": 0.35,
        "wing_focus": 0.42,
        "cross_frequency": 0.32,
        "through_ball_bias": 0.50,
        "long_ball_bias": 0.25,
        "build_up_short": 0.80,
        "offside_trap": 0.42,
        "counterpress": 0.55,
        "man_oriented_press": 0.35,
        "target_man": 0.35,
        "overlap_fullbacks": 0.48,
        "compactness": 0.72,
    },
    "total_football": {
        "pressing_intensity": 0.65,
        "risk_budget": 0.58,
        "line_height": 0.62,
        "rotation_aggressiveness": 0.92,
        "possession_orientation": 0.75,
        "verticality": 0.58,
        "width_play": 0.68,
        "tempo": 0.65,
        "counter_attack": 0.45,
        "high_press": 0.62,
        "low_block": 0.20,
        "wing_focus": 0.55,
        "cross_frequency": 0.38,
        "through_ball_bias": 0.55,
        "long_ball_bias": 0.22,
        "build_up_short": 0.72,
        "offside_trap": 0.55,
        "counterpress": 0.70,
        "man_oriented_press": 0.45,
        "target_man": 0.30,
        "overlap_fullbacks": 0.78,
        "compactness": 0.58,
    },
    "offside_trap_high_line": {
        "pressing_intensity": 0.72,
        "risk_budget": 0.55,
        "line_height": 0.82,
        "rotation_aggressiveness": 0.52,
        "possession_orientation": 0.55,
        "verticality": 0.65,
        "width_play": 0.54,
        "tempo": 0.68,
        "counter_attack": 0.48,
        "high_press": 0.75,
        "low_block": 0.15,
        "wing_focus": 0.48,
        "cross_frequency": 0.35,
        "through_ball_bias": 0.62,
        "long_ball_bias": 0.30,
        "build_up_short": 0.58,
        "offside_trap": 0.92,
        "counterpress": 0.72,
        "man_oriented_press": 0.42,
        "target_man": 0.35,
        "overlap_fullbacks": 0.55,
        "compactness": 0.62,
    },
    "possession_control": {
        "pressing_intensity": 0.55,
        "risk_budget": 0.40,
        "line_height": 0.58,
        "rotation_aggressiveness": 0.62,
        "possession_orientation": 0.85,
        "verticality": 0.42,
        "width_play": 0.58,
        "tempo": 0.50,
        "counter_attack": 0.30,
        "high_press": 0.50,
        "low_block": 0.25,
        "wing_focus": 0.48,
        "cross_frequency": 0.35,
        "through_ball_bias": 0.48,
        "long_ball_bias": 0.20,
        "build_up_short": 0.85,
        "offside_trap": 0.48,
        "counterpress": 0.58,
        "man_oriented_press": 0.32,
        "target_man": 0.32,
        "overlap_fullbacks": 0.52,
        "compactness": 0.65,
    },
    "pressing_trap": {
        "pressing_intensity": 0.78,
        "risk_budget": 0.52,
        "line_height": 0.65,
        "rotation_aggressiveness": 0.55,
        "possession_orientation": 0.48,
        "verticality": 0.68,
        "width_play": 0.52,
        "tempo": 0.72,
        "counter_attack": 0.58,
        "high_press": 0.82,
        "low_block": 0.22,
        "wing_focus": 0.48,
        "cross_frequency": 0.35,
        "through_ball_bias": 0.55,
        "long_ball_bias": 0.28,
        "build_up_short": 0.48,
        "offside_trap": 0.55,
        "counterpress": 0.80,
        "man_oriented_press": 0.62,
        "target_man": 0.35,
        "overlap_fullbacks": 0.52,
        "compactness": 0.55,
    },
    "narrow_compact": {
        "pressing_intensity": 0.45,
        "risk_budget": 0.38,
        "line_height": 0.42,
        "rotation_aggressiveness": 0.48,
        "possession_orientation": 0.55,
        "verticality": 0.50,
        "width_play": 0.28,
        "tempo": 0.48,
        "counter_attack": 0.48,
        "high_press": 0.38,
        "low_block": 0.55,
        "wing_focus": 0.22,
        "cross_frequency": 0.25,
        "through_ball_bias": 0.55,
        "long_ball_bias": 0.32,
        "build_up_short": 0.62,
        "offside_trap": 0.35,
        "counterpress": 0.45,
        "man_oriented_press": 0.40,
        "target_man": 0.45,
        "overlap_fullbacks": 0.35,
        "compactness": 0.88,
    },
    "wide_overload": {
        "pressing_intensity": 0.54,
        "risk_budget": 0.58,
        "line_height": 0.54,
        "rotation_aggressiveness": 0.60,
        "possession_orientation": 0.50,
        "verticality": 0.55,
        "width_play": 0.92,
        "tempo": 0.60,
        "counter_attack": 0.45,
        "high_press": 0.48,
        "low_block": 0.30,
        "wing_focus": 0.95,
        "cross_frequency": 0.78,
        "through_ball_bias": 0.40,
        "long_ball_bias": 0.35,
        "build_up_short": 0.50,
        "offside_trap": 0.40,
        "counterpress": 0.50,
        "man_oriented_press": 0.36,
        "target_man": 0.55,
        "overlap_fullbacks": 0.88,
        "compactness": 0.50,
    },
}

ARCHETYPE_ALIASES: Dict[str, str] = {
    "low_block_counter": "low_block_counter",
    "high_press": "high_press",
    "possession_control": "possession_control",
    "direct_vertical": "direct_vertical",
    "balanced": "balanced",
    "tiki_taka": "tiki_taka",
    "gegenpress": "gegenpress",
    "counter": "counter_attack",
    "wing": "wing_play",
    "long_ball": "long_ball",
}


def normalize_formation_key(formation: str) -> str:
    """Parse '4-3-3 - 4-2-3-1' → '433' (primary shape before alternate)."""
    if not formation:
        return "433"
    main = str(formation).split(" - ")[0].split("–")[0].strip()
    nums = re.findall(r"\d+", main.replace(" ", ""))
    if not nums:
        return "433"
    key = "".join(nums[:4])
    known = {"433", "442", "4231", "352", "532", "541", "4222", "343", "4141", "451", "3421"}
    if key in known:
        return key
    if len(nums) >= 3:
        return "".join(nums[:3])
    return "433"


def infer_archetype_from_text(style_desc: str, formation: str = "") -> str:
    """Map natural-language style (incl. Chinese) → catalog preset id."""
    d = (style_desc or "").lower()
    f = normalize_formation_key(formation)

    rules: List[Tuple[str, str]] = [
        ("tiki", "tiki_taka"),
        ("传控", "tiki_taka"),
        ("控球", "possession_control"),
        ("positional", "positional_play"),
        ("gegenpress", "gegenpress"),
        ("高位压迫", "gegenpress"),
        ("高压", "high_press"),
        ("逼抢", "high_press"),
        ("贝尔萨", "bielsa_man_marking"),
        ("全场盯人", "bielsa_man_marking"),
        ("大巴", "park_the_bus"),
        ("低位", "low_block_counter"),
        ("防反", "counter_attack"),
        ("反击", "counter_attack"),
        ("catenaccio", "catenaccio"),
        ("链式", "catenaccio"),
        ("长传", "long_ball"),
        ("高举", "long_ball"),
        ("传中", "crossing_target"),
        ("边路", "wing_play"),
        ("两翼", "wing_play"),
        ("边锋", "wing_play"),
        ("垂直", "direct_vertical"),
        ("直塞", "transitional_vertical"),
        ("false nine", "false_nine"),
        ("伪九", "false_nine"),
        ("双后腰", "double_pivot_control"),
        ("全攻全守", "total_football"),
        ("offside trap", "offside_trap_high_line"),
        ("越位陷阱", "offside_trap_high_line"),
        ("mid block", "mid_block"),
        ("中场绞肉", "mid_block"),
        ("route one", "route_one"),
        ("密集", "narrow_compact"),
    ]
    for kw, arch in rules:
        if kw in d:
            return arch
    if "5-" in f or f in ("532", "541", "523"):
        if "反击" in d or "counter" in d:
            return "low_block_counter"
        return "park_the_bus" if "守" in d or "defen" in d else "catenaccio"
    if "press" in d or "压迫" in d:
        return "gegenpress"
    if "possession" in d or "控球" in d:
        return "possession_control"
    if "counter" in d or "反击" in d:
        return "counter_attack"
    if f == "352" or f == "343":
        return "wing_play"
    return "balanced"
