#!/usr/bin/env python3
"""
Pull pass-completion baselines from StatsBomb open data (WC 2022) and write
data/calibration/statsbomb_pass_rates.json for micro passing calibration.

Requires: pip install statsbombpy pandas

Reference: https://github.com/statsbomb/open-data
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data" / "calibration" / "statsbomb_pass_rates.json"


def main() -> int:
    try:
        from statsbombpy import sb
    except ImportError:
        print("Install statsbombpy: pip install statsbombpy", file=sys.stderr)
        return 1

    country = "International"
    division = "FIFA World Cup"
    season = "2022"

    print(f"Loading {division} {season} events…")
    ev = sb.competition_events(country=country, division=division, season=season)
    passes = ev[ev["type"] == "Pass"].copy()
    if passes.empty:
        print("No pass events found.", file=sys.stderr)
        return 1

    succ = passes["pass_outcome"].isna()
    length = passes["pass_length"].astype(float)

    def bucket_rate(lo: float, hi: float) -> float:
        m = (length >= lo) & (length < hi)
        return float(succ[m].mean()) if m.any() else 0.0

    by_height = {}
    for h, grp in passes.groupby("pass_height"):
        if h is None or (isinstance(h, float) and h != h):
            continue
        by_height[str(h)] = float(grp["pass_outcome"].isna().mean())

    inter = ev[ev["type"] == "Interception"]
    failed = passes[~succ]

    payload = {
        "source": f"StatsBomb Open Data — {division} {season} ({country})",
        "fetched_note": "Auto-generated by scripts/fetch_pass_calibration_statsbomb.py",
        "n_passes": int(len(passes)),
        "overall_completion": float(succ.mean()),
        "intercept_event_ratio": float(len(inter) / max(1, len(passes))),
        "by_length_m": {
            "short_lt_15": bucket_rate(0, 15),
            "medium_15_30": bucket_rate(15, 30),
            "long_gte_30": bucket_rate(30, 999),
        },
        "by_height": by_height,
        "failed_outcome_counts": {
            str(k): int(v) for k, v in failed["pass_outcome"].value_counts().items()
        },
        "sim_targets": {
            "overall": round(float(succ.mean()), 3),
            "short": round(bucket_rate(0, 15), 3),
            "through": round(bucket_rate(15, 30) * 0.84, 3),
            "long": round(bucket_rate(30, 999), 3),
            "intercept_share_max": 0.05,
        },
    }

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"Wrote {OUT}")
    print(f"  overall={payload['overall_completion']:.1%}  intercept/pass={payload['intercept_event_ratio']:.1%}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
